spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini_pg?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379

pg:
  fake:
    base-url: http://localhost:8080
    timeout-ms: 2000
  cache:
    ttl:
      approved-seconds: 60
      declined-seconds: 60
      pending-seconds: 10
      not-found-seconds: 2
